// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xucazaubgneefqwvdapw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1Y2F6YXViZ25lZWZxd3ZkYXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTQwNjMsImV4cCI6MjA1OTk5MDA2M30.8yYxUcAXI14d4M3niZE-4YsNZclJlLRKnLvN4B5YtrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);